### ISSUE TITLE
Using the latest stable SciPy release (version 1.14.0) will cause USpekPy to crash

### ISSUE THREAD

**Issue by pazaviles** [lmri-met/uspekpy#9]
**Details**: 

- The function scipy.integrate.trapz has been recently deprecated in favor of scipy.integrate.trapezoid as of the latest stable SciPy release (version 1.14.0).
- The SpekPy library v. 2.0.11.1 uses this function of SciPy, and the SpekPy library v. 2.0.11.1 itself is a dependency of USpekPy library.

**Solution**:

- Users are advised to use a previous version of SciPy.  It has been checked that USpekPy works properly with SciPy version 1.13.1. 

**Further actions**:

- SpekPy developers have been warned today about this issue. Dependencies of USPekPy will be updated and a new version will be released as soon as this issue is fixed.
- An informative note will be added to USpekPy documentation (README file in the repository) and an issue will be opened until the bug is fixed.
- Meanwhile, USpekpy can be used taking into account the solution stated earlier.

**Acknowledgments**:

- To Jean Marc Bordy, who brought this issue to our attention.

**Comment by xandratxan** [comment]
- SpekPy developers **fixed the bug** and released a new version (2.0.12) on BitBucket.
- We have **published** Spekpy version 2.0.12 **to PyPi**.
- We have check that the current version of **USpekPy** works properly **without the need of releasing a new version**.
- When **installing USpekPy** as of today, the latest versions of SciPy (version 1.14.0) and SpekPy (version 2.0.12) are installed.
- Users with USpekPy already installed are **recommended to reinstall USpekPy in a clean environment** to avoid dependencies issues.
